name: JoinDate
version: ${project.version}
main: com.turbotailz.joindate.JoinDate
api-version: '1.13'
softdepend: [PlaceholderAPI]
authors: [Turbotailz, KJNine]
description: A plugin that lets players check the date they joined a server
website: https://turbotailz.com
commands:
  joindate:
    description: Check your join date.
    usage: /joindate
    aliases: [jd]
permissions:
  joindate.check:
    description: Allows joindate command
    default: op
  joindate.check.others:
    description: Allows checking other players with joindate
    default: op
  joindate.bynumber:
    description: Allows checking which player was number X
    default: true